# fly.toml (na RAIZ do reposit√≥rio)
app = "takehome-worker-SEU-SUFIXO"
primary_region = "gru"

[build]
  dockerfile = "worker/Dockerfile"   # <- caminho do Dockerfile dentro do repo

[env]
  UVICORN_WORKERS = "1"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  concurrency = { type = "requests", hard_limit = 80, soft_limit = 60 }

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"

[checks]
  [checks.health]
    port = 8000
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/healthz"
